# https://docs.readthedocs.io/en/stable/config-file/v2.html
version: 2

python:
   version: 3.7
   install:
      - requirements: requirements.txt
sphinx:
   configuration: conf.py


submodules:
  include: all